### PR TITLE
Adding typescript support to generator-angular

### PR DESCRIPTION
**Pull request by eggers**
There have been a few other projects that have tried to support typescript with the angular generator (e.g. [anchann](https://github.com/anchann/generator-angular) and [JakubMrozek](https://github.com/JakubMrozek/generator-angular-typescript)), but are currently out of date. It would be great if we could get this merged in so that we can try keeping it current.

### CODE REVIEW

**Comment by moneytree-doug** [comment]
:+1:  Any updates?

**Comment by luisrudge** [comment]
I think its best to create a generator-angular-typescript and be done with it. No one from this project really care, unfortunately.

**Comment by mohlman3** [comment]
+1

**Comment by keichi** [comment]
+1 for this.

**Comment by reroslyn** [comment]
+1 for this!

**Comment by awk** [comment]
This pull request seems to have gone stale in the past 6-8 months. I just created https://github.com/yeoman/generator-angular/pull/1098 which is based on this one but with updates for the latest version of generator-angular and also to use tsd/definitelyTyped to pull the .d.ts files

**Comment by danielsiwiec** [comment]
+1

**Comment by rogerpadilla** [comment]
+1

**Comment by javarch** [comment]
Ich werde ab  19.10.2015 nicht im B�ro sein. Ich kehre zur�ck am
23.10.2015.
Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten.

Die R�ckmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [generator-angular] Adding typescript support to generator-angular
(#539)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2015 Agent 'Abwesenheit'

Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angef�hrten Absender via E-Mail
dient ausschlie�lich Informationszwecken. Rechtsgesch�ftliche Erkl�rungen
d�rfen �ber dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.

**Comment by eddiemonge** [comment]
why are you `+1` this? its already been added

**Pull request closed without merging**
