### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by kutec**
Updating hyperlinks

### CODE REVIEW

**Comment by kutec** [comment]
Why this has not been pulled? I faced issue redirecting from one page from the other under navigation section.

**Comment by eddiemonge** [comment]
this only works if angular 1.6 is installed. if angular 1.5 then it breaks

**Comment by arimourao** [comment]
But if it is the 1.6, and certainly 1.6 will be the most used in new projects from now on, its broken. How can we deal with that?

**Comment by kutec** [comment]
Can anyone please update whether this is going to be merged or not?

**Pull request merged**
