### PR TITLE
feat(release): use github releases instead of CHANGELOG

### PR DESCRIPTION
**Pull request by stevemao**
You need to set environment variable GH_TOKEN as your github token.

### CODE REVIEW

**Comment by eddiemonge** [comment]
forgot to remove the actual changelog as well but otherwise looks good

**Comment by eddiemonge** [comment]
What scopes are needed for the token?

**Comment by stevemao** [comment]
It's now `GH_TOKEN` but I can change this if you want.

**Comment by stevemao** [comment]
I changed it to `GITHUB_AUTHTOKEN` as I see you already using it

**Comment by stevemao** [comment]
I have fixed the problems. Can you please try it?

**Pull request merged**
