### PR TITLE
fix(changelog): add repository to generate correct absolute path

### PR DESCRIPTION
**Pull request by stevemao**
fix(changelog): add repository to generate correct absolute path
docs(changelog): fix links

### CODE REVIEW

**Comment by sindresorhus** [comment]
:-1: The changelog module should just get it from package.json.

**Comment by stevemao** [comment]
Submitting a PR, but that repo doesn't seem to be very actively maintained.

**Comment by sindresorhus** [comment]
@stevemao I know Brian. I'm sure he'll add you to the repo if you ask ;)

**Comment by stevemao** [comment]
Thanks @sindresorhus , that repo looks not too busy and might be a good start point for me :D

**Comment by sindresorhus** [comment]
*Also totally OT, but get yourself some kind of avatar on GitHub. I get so much spam issues from avatar-less users it would be too easy to dismiss you.*

**Comment by stevemao** [comment]
LOL will do that soon :D

**Comment by eddiemonge** [comment]
closing this for that. asked brian for permissions on that repo

**Pull request closed without merging**
