### PR TITLE
Wrapping all files in IIFEs to avoid polluting the global scope.

### PR DESCRIPTION
**Pull request by marclloyd77**
Hi,
It's good practice to wrap Angular components in Immediately Invoked Function Expression's to avoid polluting the global scope.

### CODE REVIEW

**Comment by realityking** [comment]
IMO it would make more sense to to wrap the concatenated file in an IIFE, unfortunately I've never gotten that to work with usemin.

**Comment by marclloyd77** [comment]
The reason for wrapping each individual module/function is to isolate it's scope to avoid any conflicts when the files have been concatenated and minified. Wrapping the whole concatenated file wouldn't achieve this.

**Comment by realityking** [comment]
Well not of these files, as generated, export anything as they just register things with Angular. In the end this only bloats the code unnecessarily.

**Comment by eddiemonge** [comment]
I agree that this only adds bloat. Developers who know to use this can setup to do it. Like @realityking said, wrapping the whole file would be better. Also, CoffeeScript (and I assume TypeScript and other tools) will do this for you as well.

If this were to be added, I'd like to see two things done: 

1. Pass in window or angular to the IIFE to make it really not use global scope
2. Have these wrapped in a tool instead of in pure code like this is. This will help with developer typo errors and other things.

**Comment by marclloyd77** [comment]
Hi Guys,

No problem. I've been trying to adhere to the two main AngularJS style guides by John Papa and Todd Motto. These make sense to me but maybe I'm not fully understanding it.

https://github.com/johnpapa/angular-styleguide#iife
https://github.com/toddmotto/angularjs-styleguide

**Comment by eddiemonge** [comment]
If you can get the build script to wrap the individual files that works as well.

**Pull request closed without merging**
